### ISSUE TITLE
ModuleNotFoundError: No module named 'aiida_wannier90_workflows'

### ISSUE THREAD

**Issue by ahzeeshan** [aiidateam/aiida-wannier90-workflows#12]
Hi, I installed this workflow using pip but when running got the following error (using python 3.8.6):

```
(aiida) ➜  aiida_calcs ./run_automated_wannier.py GaAs.xsf
Structure AsGa read and stored with pk 375.
Running with conduction bands for AsGa
Wannier90BandsWorkChain<384> will be added to the group scdm_workflow_withconduction_mlwf that already contains 4 nodes
launched Wannier90BandsWorkChain pk 384 for structure AsGa

# To get a detailed state of the workflow, run:
verdi process report 384
(aiida) ➜  aiida_calcs verdi process report 384
2021-01-08 07:40:09 [11 | ERROR]: Traceback (most recent call last):
  File "/Users/zeeshan/miniconda3/envs/aiida/lib/python3.8/site-packages/aiida/engine/persistence.py", line 42, in load_object
    module = importlib.import_module(module)
  File "/Users/zeeshan/miniconda3/envs/aiida/lib/python3.8/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 961, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 961, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 973, in _find_and_load_unlocked
ModuleNotFoundError: No module named 'aiida_wannier90_workflows'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/zeeshan/miniconda3/envs/aiida/lib/python3.8/site-packages/aiida/manage/external/rmq.py", line 201, in _continue
    result = yield super()._continue(communicator, pid, nowait, tag)
  File "/Users/zeeshan/miniconda3/envs/aiida/lib/python3.8/site-packages/tornado/gen.py", line 1055, in run
    value = future.result()
  File "/Users/zeeshan/miniconda3/envs/aiida/lib/python3.8/site-packages/tornado/concurrent.py", line 238, in result
    raise_exc_info(self._exc_info)
  File "<string>", line 4, in raise_exc_info
  File "/Users/zeeshan/miniconda3/envs/aiida/lib/python3.8/site-packages/tornado/gen.py", line 307, in wrapper
    yielded = next(result)
  File "/Users/zeeshan/miniconda3/envs/aiida/lib/python3.8/site-packages/plumpy/process_comms.py", line 541, in _continue
    proc = saved_state.unbundle(self._load_context)
  File "/Users/zeeshan/miniconda3/envs/aiida/lib/python3.8/site-packages/plumpy/persistence.py", line 51, in unbundle
    return Savable.load(self, load_context)
  File "/Users/zeeshan/miniconda3/envs/aiida/lib/python3.8/site-packages/plumpy/persistence.py", line 438, in load
    load_cls = load_context.loader.load_object(class_name)
  File "/Users/zeeshan/miniconda3/envs/aiida/lib/python3.8/site-packages/aiida/engine/persistence.py", line 44, in load_object
    raise ImportError(f"module '{module}' from identifier '{identifier}' could not be loaded")
ImportError: module 'aiida_wannier90_workflows.workflows.bands' from identifier 'aiida_wannier90_workflows.workflows.bands:Wannier90BandsWorkChain' could not be loaded
```

**Comment by ahzeeshan** [comment]
Can't reproduce this. Closing.
